/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e5e2e1",
        "surface-container-low": "#f6f3f2",
        "tertiary-fixed": "#ffdcc1",
        "on-error": "#ffffff",
        "background": "#ffffff",
        "tertiary": "#693800",
        "on-primary": "#ffffff",
        "primary-container": "#000000",
        "on-secondary-fixed": "#1b1c1c",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#ffcaa0",
        "secondary-container": "#f5f5f7",
        "tertiary-fixed-dim": "#ffb779",
        "on-tertiary": "#ffffff",
        "surface-container": "#f5f5f7",
        "outline": "#d2d2d7",
        "on-error-container": "#93000a",
        "tertiary-container": "#8b4c00",
        "surface-tint": "#000000",
        "inverse-on-surface": "#f3f0ef",
        "on-secondary-fixed-variant": "#464747",
        "primary-fixed": "#dee0ff",
        "surface-bright": "#ffffff",
        "secondary": "#86868b",
        "outline-variant": "#e5e5e7",
        "surface-container-highest": "#e5e2e1",
        "on-surface": "#1d1d1f",
        "on-background": "#1d1d1f",
        "on-secondary-container": "#1d1d1f",
        "error": "#ba1a1a",
        "inverse-surface": "#303030",
        "on-tertiary-fixed-variant": "#6c3a00",
        "secondary-fixed-dim": "#c7c6c6",
        "inverse-primary": "#bac3ff",
        "surface-container-high": "#eae7e7",
        "on-tertiary-fixed": "#2e1500",
        "surface-dim": "#dcd9d8",
        "primary-fixed-dim": "#bac3ff",
        "on-primary-fixed-variant": "#2c3e98",
        "primary": "#0071e3",
        "on-primary-container": "#ffffff",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#e4e2e2",
        "on-surface-variant": "#424245",
        "on-primary-fixed": "#00105a",
        "surface": "#ffffff",
        "error-container": "#ffdad6"
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.25rem",
        full: "9999px"
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Source Code Pro", "monospace"]
      }
    },
  },
  plugins: [],
}
